// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schv3.Data;

#nullable disable

namespace Schv3.Migrations
{
    [DbContext(typeof(AppDataDbContext))]
    [Migration("20221128190317_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Schv3.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Group_Code")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Classroom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Subject")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Teacher")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Schv3.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("Schv3.Models.Group", b =>
                {
                    b.Property<int>("GrouoCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("course")
                        .HasColumnType("INTEGER");

                    b.Property<int>("education")
                        .HasColumnType("INTEGER");

                    b.Property<int>("study_form")
                        .HasColumnType("INTEGER");

                    b.HasKey("GrouoCode");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Schv3.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_1Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_2Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_3Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_4Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_5Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_6Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_7Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_8Class")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("date")
                        .HasColumnType("TEXT");

                    b.Property<int>("week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Schv3.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_teacher")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Schv3.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
